Update article
Wolox/conduit-react-native pull request #15
Opened 2021-08-16 05:58 UTC by andyOlarte514

## Summary
- Update Article

## Screenshots

### Android
![image](https://user-images.githubusercontent.com/40371687/129517715-8e85bb3f-9468-4455-a54f-8abdd8812500.png)
![image](https://user-images.githubusercontent.com/40371687/129517737-bc7eb4b1-d741-4100-807c-7382d7a55250.png)

### iOS
![image](https://user-images.githubusercontent.com/40371687/129517347-f0d05915-ee2d-4229-908b-cfcf25acf5e1.png)
![image](https://user-images.githubusercontent.com/40371687/129517363-4b65a3af-20ca-4073-9f6e-8923752a6533.png)

## Trello Card
- https://trello.com/c/VyNKUFIG/8-update-article

2021-08-18 15:08 UTC, EstebanIndiveri requested changes
great! I have only 2 comments

2021-08-18 15:08 UTC, EstebanIndiveri commented on src/app/screens/DetailArticle/index.tsx
> +      <View style={styles.containerActions}>
They can't be visible when user isn't login, can you use?
const currentUser = useSelector((state: State) => state.auth.currentUser);
{currentUser &&( ....)}

2021-08-18 15:08 UTC, EstebanIndiveri commented on src/app/screens/DetailArticle/index.tsx
> +function DetailArticle({ route, navigation }: Props) {
what do you think about this :

 interface Props {
  route: {
    params: {
      article: Article;
    };
  };
}
and navigation from: import useNavigation from '@components/AppNavigator/helper'; 
if you don't like ignore this

2021-08-18 19:10 UTC, EstebanIndiveri approved these changes
good Job !!

2021-08-23 15:13 UTC, santiagorobra commented on src/app/screens/DetailArticle/index.tsx
> +export interface Props {
I think this interface is going to be repeated a lot, could you make a general one?

route: {
    params: {
      
    };
  };

2021-08-24 12:53 UTC, santiagorobra approved these changes

2021-08-24 15:19 UTC, merged